# Generated by Django 4.2.11 on 2024-05-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='updated_on',
        ),
    ]
