<<<<<<< HEAD
# Generated by Django 4.2.11 on 2024-05-03 21:06
=======
# Generated by Django 4.2.11 on 2024-05-03 15:09
>>>>>>> 6b36b6eb679a59467697eb515fb35cac7c478886

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_recipe_options_remove_recipe_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='body',
        ),
    ]
