# Generated by Django 4.2.11 on 2024-05-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
