# Generated by Django 4.2.11 on 2024-05-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Share',
            new_name='ShareABook',
        ),
    ]
